package usagesync

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// SchemaVersion is the usage file schema the snapshot is written in. The
// synced, series and errors keys are additions the existing loader
// ignores, so older versions still read the quantities.
const SchemaVersion = "0.1"

// Snapshot is the generated usage file.
type Snapshot struct {
	Version       string                    `yaml:"version"`
	Synced        Meta                      `yaml:"synced"`
	ResourceUsage map[string]map[string]any `yaml:"resource_usage"`
	// Series holds per-month values: address, then key, then "YYYY-MM".
	Series map[string]map[string]map[string]float64 `yaml:"series,omitempty"`
	// Errors says, per resource, why a value is missing.
	Errors map[string]string `yaml:"errors,omitempty"`
}

// Meta describes how a snapshot was made.
type Meta struct {
	Provider    string    `yaml:"provider"`
	WindowDays  int       `yaml:"window_days"`
	GeneratedAt time.Time `yaml:"generated_at"`
}

const header = "# Generated by `c3x usage sync`. Replaced on every run; do not edit.\n" +
	"# Put overrides in the hand-written usage file, which wins per key.\n"

// Marshal renders the snapshot. Map keys are sorted by the encoder, so
// the same measurements produce the same bytes apart from generated_at.
func (s Snapshot) Marshal() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(s); err != nil {
		return nil, fmt.Errorf("encode snapshot: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("encode snapshot: %w", err)
	}
	return buf.Bytes(), nil
}

// Write replaces the file at path with the snapshot. It writes a temporary
// file in the same directory and renames it, so a reader never sees a
// half-written file and a failed run leaves the previous snapshot intact.
func (s Snapshot) Write(path string) error {
	data, err := s.Marshal()
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".c3x-usage-synced-*")
	if err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
